name: Get Unity License File

# Run manually â€” you only need this once
on:
  workflow_dispatch: {}

jobs:
  request-alf:
    name: Request activation file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.3.10f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.3.10f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
